Tugas 1 Praktikum Basis Data
yukiao/Asistensi-07-Lab-Database-2022 pull request #2
Opened 2022-09-22 12:37 UTC by zabilsabri

Nama: Zabil Sabri Muhammad
NIM: H071211016

2022-09-25 03:28 UTC, yukiao requested changes

2022-09-25 03:28 UTC, yukiao commented on H071211016/Pertemuan-1/assignment_1_5.sql
> +	tahun_terbit INT,
## Perbaikan
`tahun_terbit` -> `tahun terbit` (gunakan tanda ` untuk membuat string dengan spasi)

2022-09-25 09:25 UTC, zabilsabri commented on H071211016/Pertemuan-1/assignment_1_5.sql
> +	tahun_terbit INT,
Iye kak

2022-10-11 01:39 UTC, yukiao approved these changes

2022-10-11 01:39 UTC, merged